version: '3'
services:
  db:
    image: mysql:8.0.17
    container_name: nodejs-textbook-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nodejs
      MYSQL_USER: rawcoder
      MYSQL_PASSWORD: password
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Users/comi/db/mysql:/var/lib/mysql